# Generated by Django 5.2.6 on 2025-09-08 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('place', models.CharField(max_length=200)),
                ('number_of_actors', models.IntegerField()),
                ('meeting_time', models.TimeField()),
                ('meeting_date', models.DateField()),
                ('meeting_place', models.CharField(max_length=200)),
                ('transport_vehicle', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('camera_man', models.CharField(max_length=100)),
                ('dress_details', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actors', models.ManyToManyField(related_name='parties', to='authentication.actor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parties',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='authentication.party')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
