# Generated by Django 5.2.6 on 2025-09-08 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='can_manage_actors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='can_manage_parties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='can_view_all_actors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='can_view_completed_parties',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='can_view_upcoming_parties',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
