# Generated by Django 5.2.6 on 2025-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_actor_can_manage_actors_actor_can_manage_parties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='can_access_actors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='can_access_dashboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='can_access_parties',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actor',
            name='can_access_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
