# Generated by Django 5.2.6 on 2025-09-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_actor_can_access_actors_actor_can_access_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
