# Generated by Django 5.2.6 on 2025-09-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_song_artist_song_duration_song_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='notes',
        ),
    ]
