# Generated by Django 5.2.6 on 2025-09-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_song_artist_remove_song_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='event',
            field=models.CharField(default='Other', help_text='Type of event (e.g., Wedding, Birthday, etc.)', max_length=200),
        ),
    ]
